### ISSUE TITLE
Add option to stream and save homebrew from internal storage and SD instead of storing in memory

### ISSUE THREAD

**Issue by SegFault42** [misson20000/twili#58]
I'm trying to launch homebrew with twib and i got this error : 

```
~/Documents/GameOfLife(master) » twib run -a ./hello.nro                                                                                        segfault42@segfault42-pc
terminate called after throwing an instance of 'twili::twib::ResultError'
  what():  ResultError: 0x6dd
[1]    14707 abort (core dumped)  twib run -a ./hello.nro
```

Everything is working fine (twib list-devices, ps, identify ...) except twib run.

Switch firmware : 5.1.0

Tested with Atmosphere 0.8.2

**Comment by misson20000** [comment]
This is `LIBTRANSISTOR_ERR_OUT_OF_MEMORY`. Your NRO is likely too big for Twili to store in memory. I've been considering this for a while, so I think I'll add options to stream to SD card or internal storage.
