### ISSUE TITLE
Boot on Atmosphere without twili loaded

### ISSUE THREAD

**Issue by SegFault42** [misson20000/twili#66]
Hi, 

Any tips to launch Atmosphere without twili ?

Thank you

**Comment by misson20000** [comment]
Remove `boot2.flag` from Twili's title directory, or alternatively just delete/move elsewhere all of Twili's title directories (atmosphere/titles/0100...00648x/). You will also need to put back [stock nx-hbloader](https://github.com/switchbrew/nx-hbloader/releases).

**Comment by SegFault42** [comment]
Perfect, thank you.
