### ISSUE TITLE
hbmenu doesn't work until usb connected

### ISSUE THREAD

**Issue by mossvr** [misson20000/twili#79]
I've noticed that some features do not work until the switch has been connected to twibd via usb at least once. If I try to start the homebrew menu without first connecting via usb, it gets stuck on a blank screen and does not launch the homebrew menu. Likewise, I cannot connect to twili via tcp until the usb has been connected at least once.

I'm using Twili 1.2.1 on Atmosphere 0.8.9

**Comment by mossvr** [comment]
It stops doing this after disabling usb_bridge in twili.ini

**Comment by mcd1992** [comment]
Noticed the same thing, I thought something was wrong with the hbl.nsp at first. Might be worthwhile to just throw something in the readme.md about first time setup needing a usb connection.

**Comment by misson20000** [comment]
Disabled synchronous USB logging by default in https://github.com/misson20000/twili/commit/1f86c862166c62c6613b49790998df2a2247fcb4.
