### ISSUE TITLE
FS Calls don't work while running a sysmodule through Twili/Twib

### ISSUE THREAD

**Issue by lucyyyyyyy** [misson20000/twili#91]
fopen doesn't work and trying to use mkdir hangs the sysmodule. https://discordapp.com/channels/269333940928512010/383368936466546698/619213690964803607

**Comment by misson20000** [comment]
Fixed with ECSProcess! https://github.com/misson20000/twili/commit/cf6b06f07331fa30e02d88781535e91888f46fe4.
