### ISSUE TITLE
Can't run nros as sysmodules in current version

### ISSUE THREAD

**Issue by jakibaki** [misson20000/twili#95]
On current version when launching custom nros it never seems to get to the point of running any code.

Going by a coredump the nro gets loaded into memory successfully but no code actually executes.  
Same nro works just fine on twili 1.2.0.

further details here: https://discordapp.com/channels/269333940928512010/404722395845361668/631868109887635496

**Comment by misson20000** [comment]
Let me know if this persists with ECSProcess once I put out the next release.

**Comment by misson20000** [comment]
Going to assume this was fixed with ECSProcess.
